# Generated by Django 3.1.6 on 2021-02-09 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
