# Generated by Django 3.1.6 on 2021-02-09 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210209_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
