# Generated by Django 3.1.6 on 2021-02-16 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210216_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
