# Generated by Django 3.1.6 on 2021-02-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_mybook_acc_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
