# Generated by Django 3.1.6 on 2021-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='idea',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mybook',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mybook',
            name='sentence',
            field=models.TextField(null=True),
        ),
    ]
