# Generated by Django 3.1.6 on 2021-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20210216_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(default='default', max_length=20)),
                ('isbn', models.CharField(max_length=100)),
                ('sentence', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='sentence',
        ),
    ]
