# Generated by Django 3.1.6 on 2021-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20210217_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='page',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
