# Generated by Django 3.1.6 on 2021-02-16 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_sentence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
